config/routes.rb
TasklistChallenge::Application.routes.draw do
  resources :tasks, exclude: [:show]
  root 'tasks#index'

  get 'readme' => 'docs#readme', as: :readme
  get 'maps' => 'maps#show', as: :maps
end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :user  # Add multi-user support

  {
    complete: { completed: true, incomplete: false },
    archived: { archived: true, unarchived: false }
  }.each do |attribute, scopes|
    scopes.each do |scpe, value|
      scope scpe, lambda { where(attribute => value) }
    end

    define_method "#{attribute}!" do
      update_attribute(attribute, true)
    end
  end
end

app/models/user.rb
# Add multi-user support

class User < ActiveRecord::Base

  has_many :tasks

  validates :name,   presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
# encoding: utf-8

# Display Markdown documents to the user.

class DocsController < ApplicationController

  # displays 'tasklist.md', 'comments.md', and 'section_E.md' to the viewer.
  def readme
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def show
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @task = Task.new

    if params.key?('q')
      @archived = nil
      @query = "%#{params['q']}%"  # Fix issues with task searching

      @tasks = Task.where(
        Task.arel_table[:title].matches(@query).or(
          Task.arel_table[:description].matches(@query)
        )
      )
    else
      @tasks = Task.all

      @archived = params.key?('archived') && params['archived'] == 'true'
      @tasks.where!(archived: true) if @archived
      @tasks = @tasks.unarchived unless @archived
    end
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_path, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
        format.js   { head :no_content }  # Add archive support
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
        format.js   { render json: @task.errors, status: :unprocessable_entity }  # Add archive support
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :complete, :archived, :tags)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Add Google Maps integration
  def maps_controller?
    controller.controller_name == 'maps'
  end

end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/docs/readme.html.haml
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        = link_to 'My Tasks', root_path, class: 'btn btn-default pull-right'
        %h4 tasklist.md
      .panel-body
        :markdown
          #{IO.read('tasklist.md')}

    .panel.panel-default
      .panel-heading
        %h4 comments.md
      .panel-body
        :markdown
          #{IO.read('comments.md')}

    .panel.panel-default
      .panel-heading
        %h4 section_E.md
      .panel-body
        :markdown
          #{IO.read('section_E.md')}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task List Challenge</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?sensor=false" if maps_controller? %>  <!-- Add Google Maps integration -->
  <%= csrf_meta_tags %>
</head>
<body>

<div class='container'>
  <%= yield %>
</div>

</body>
</html>

app/views/maps/show.html.haml
.row
  .col-md-12
    .panel.panel-default.map-view#map
      [D] Add Google Maps Integration!

/ Add Google Maps integration
#map-canvas

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%- if @task.new_record? %>
    <%= f.hidden_field :archived, value: false %>
    <%= f.hidden_field :complete, value: false %>
  <%- else %>

      <div class='form-inputs'>
        <%= f.label :complete %>:
        <%= f.check_box :complete %>
      </div>
      <div class='form-inputs'>
        <%= f.label :archived %>:
        <%= f.check_box :archived %>
      </div>
  <%- end %>


  <div class='form-inputs'>
    <div class="input-group">
      <div class='input-group-addon'>
        <%= f.label :title %>
      </div>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class='form-inputs'>
    <div class="input-group">
      <div class='input-group-addon'>
        <%= f.label :description %>
      </div>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tasks/_search_form.html.erb
<%= form_for(?:, url: tasks_path, method: :get) do |f| %>
  <div class='form-inputs'>
    <div class="input-group">
      <%= f.text_field :q, name: :q, class: 'form-control' %>
      <div class='input-group-btn'>
        <%= f.button 'Search', name: nil, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class='row'>
  <div class='col-md-12'>
    <div class='panel panel-default'>
      <div class='panel-heading'>
        <h4>Editing Task: <%= raw @task.title %></h4>  <!-- Fix issue where edit view shows HTML as TEXT -->
      </div>

      <div class='panel-body'><h1></h1>

        <%= render 'form' %>

        <%= link_to 'Back', tasks_path %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class='row'>
  <div class='col-md-12'>
    <div class='panel panel-default'>
      <div class='panel-heading'>
        <div class='pull-right btn-group'>
          <%=
            link_to tasks_path(archived: !@archived), class: 'btn btn-default' do
              if @archived
                'View Unarchived Tasks'
              else
                'View Archived Tasks'
              end
            end
          %>
          <%= link_to 'View README', readme_path, class: 'pull-right btn btn-default' %>
        </div>
        <h4>My Tasks</h4>
      </div>

      <div class='panel-body panel-action'>
        <%= render 'form' %>
      </div>

      <div class='panel-body'>
        <%= render 'search_form' %>
      </div>
      <!-- Add complete support -->
      <table id='task-list' class='table table-striped'>
        <thead>
          <tr>
            <th>Complete</th>
            <th>Task</th>
            <th>Description</th>
            <th class='actions'></th>
          </tr>
        </thead>

        <tbody>
          <% @tasks.each do |task| %>
            <tr class='task'> <!-- Add archive support -->
              <!-- Add complete support -->
              <td>
                <%= check_box_tag :complete, :complete, task.complete, data: { 'url' => task_path(task) } %>
                <% if task.complete %>  <!-- Style completed tasks -->
                  <span class="label label-success">Done</span>
                <% end %>
              </td>
              <td><%= task.title.html_safe %></td>
              <td><%= task.description.html_safe %></td>
              <td class='horizontal-button-grp'><!-- Style buttons -->
                <%= link_to 'Edit', edit_task_path(task), class: 'btn btn-default btn-sm' %>
                <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
                <!-- Add archive support -->
                <%= link_to task.archived ? 'UnArchive' : 'Archive',
                  task_path(task, 'task[archived]' => !task.archived), remote: true, method: 'PUT', class: 'btn btn-warning btn-sm archive'
                %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>